project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    # Examples:
    # url(r'^$', 'project.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),
    url(r'^countrylist/$','main.views.countrylist'),
    url(r'^country/(?P<pk>\d+)/$','main.views.countrydetail'),
    url(r'^createcountry/$','main.views.createcountryform'),
    url(r'^sign_up/$', 'main.views.sign_up'),
    url(r'^signin/$', 'main.views.signin'),
    url(r'^signout/$', 'main.views.signout'),
    url(r'^editreview/(?P<pk>\d+)/$', 'main.views.editreview'),
    url(r'^deletereview/(?P<pk>\d+)/$', 'main.views.deletereview'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.
class Country(models.Model):
	name= models.CharField(max_length=255, unique=True)
	capital = models.CharField(max_length=255,null=True,blank=True)
	population = models.IntegerField(null=True,blank=True)
	flag = models.ImageField(null=True,blank=True,upload_to='flags')
	 
	def __unicode__(self):
		return self.name


class Review(models.Model):
	title = models.CharField(max_length=255)
	content = models.TextField()
	date = models.DateTimeField(auto_now_add=True)
	country = models.ForeignKey(Country)
	user = models.ForeignKey(User)
	def __unicode__(self):
		return self.title

main/forms.py
from django import forms	
from main.models import Country, Review

class CreateCountryForm(forms.ModelForm):
	class Meta:
		model = Country
		fields = '__all__'
		#exclude = ('flag',)

class CreateUserForm(forms.Form):
	username = forms.CharField(max_length=30)
	password = forms.CharField(max_length=30, widget=forms.PasswordInput())
	email = forms.EmailField(required=False)


class SignInForm(forms.Form):
	username = forms.CharField(max_length=30)
	password = forms.CharField(max_length=30, widget=forms.PasswordInput())


class CreateReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		exclude = ('date' , 'country','user')
		#fields = "__all__"


class EditReviewForm(forms.ModelForm):
	class Meta:
		model = Review
		exclude = ('date','country','user')

main/views.py
from django.shortcuts import render, redirect
from models import Country
from forms import CreateCountryForm, CreateUserForm, SignInForm , CreateReviewForm , EditReviewForm
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.contrib.auth  import authenticate, login , logout
from django.contrib.auth.models import User
from datetime import datetime
# only admin ALLOWED
from django.contrib.admin.views.decorators import staff_member_required


# Create your views here.
def countrylist(request):
	context = {}
	countries = Country.objects.all()
	context['country_list'] = countries
	print context
	return render(request, 'country_list.html', context)

def countrydetail(request, pk):
	context = {}
	country = Country.objects.get(pk=pk)
	context['country'] = country
	

	if request.method == 'POST':
		form = CreateReviewForm(request.POST)
		context['form'] = form
		if form.is_valid():
			review = form.save(comit=False)
			review.date = datetime.now()
			review.country = country
			review.user =request.user
			review.save()
			return redirect('/countrylist/')

	return render(request, 'country_detail.html', context)


@login_required
def createcountryform(request):
	context = {}
	context['form'] =  CreateCountryForm()

	if request.method == 'POST':
		#make sure form is valid
		form = CreateCountryForm(request.POST)
		context['form'] = form

		if form.is_valid:
			form.save()
			return render(request, 'countrycreated.html', context)
		#save form to database
	return render(request, 'CreateCountry.html', context)



def sign_up(request):
	context = {}
	context['form'] = CreateUserForm()

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		context['form'] == form
		if  form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			email = form.cleaned_data['email']
			#print username
			new_user = User.objects.create_user(username=username, password=password)
			new_user.save()
			
			auth_user = authenticate(username=username, password=password)
			login(request, auth_user)

			return redirect('/countrylist/')

	return render(request, 'sign_up.html', context)


def signin(request):
	context = {}
	context['form'] = SignInForm()

	if request.method == 'POST':
		form = SignInForm(request.POST)
		context['form'] == form
		if form.is_valid():
			username = form.cleaned_data['username']
			password = form.cleaned_data['password']
			try:
				auth_user = authenticate(username=username , password=password)
				login(request, auth_user)
				return redirect('/countrylist/')

			except Exception, e:
				return HttpResponse('')

			

	return	render(request, 'signin.html' , context)


def signout(request):
	logout(request)
	return redirect('/countrylist/')	


@login_required
def editreview(request,pk):
	context = {}
	review = Review.objects.get(pk=pk)
	if request.user == review.user:
		context['review'] = review
		form = EditReviewForm(request.POST or None, instance=review)

		context['form'] = form

		if form.is_valid():
			form.save()
			return redirect ('/countrylist/')

	else:
		return HttpResponse('GO AWAY HACKER !!')

	return render(request, 'editreview.html' , context)


def deletereview(request,pk):
	review = Review.objects.get(pk=pk)

	if request.user == review.user:
		review.delete()

	return redirect('/countrylist/')

main/templates/CreateCountry.html
{% extends 'base.html' %}

{% block body %}


<form action="/createcountry/" method="POST" enctype="multipart/form-data">


{% csrf_token %}
{{form.as_p}}

<input type="submit" value="Create Country">
</form>


{% endblock %}

main/templates/country_detail.html
{% extends 'base.html' %}



{% block body %}

<h1>Country List</h1>
<p>{{country.name}}</p>
<p>{{country.population}}</p>
<p>{{country.capital}}</p>

{% if country.flag %}
	<p> <img src='{{country.flag.url}}'> </p>
{% endif %}

<br><br>

{% for review in country.review_set.all %}

	<h2>{{review.title}}</h2>

	{% if request.user == review.user %}
	<a href="/editreview/{{review.pk}}"><p>EDIT</p></a>
	<a href="/deletereview/{{review.pk}}"><p>DELETE</p></a>
	{% endif %}
	<p>content : {{review.content}}</p>
	<p>review by : {{review.user}}</p>


	<hr>
{% endfor %}



{% if user.is_authenticated %}

<form action='/country/{{country.pk}}/' method='POST'>
	
{% csrf_token %}
	
{{form.as_p}}
	
<input type='submit' value='Add Review'>

</form>

{% endif %}


{% endblock %}

main/templates/country_list.html
{% extends 'base.html' %}

{% block body %}

<h1>Country list</h1>

{% if user.is_authenticated %}
<a href='/createcountry/'><h3>add country</h3></a>
{% endif %}

{% for country in country_list %}

<a href="/country/{{country.pk}}">{{country.name}}</a>

<br><br>
{% endfor %}




{% endblock %}

main/templates/countrycreated.html
{% extends 'base.html' %}

{% block body %}

<h1>COUNTRY SUCCESSFULLY CREATED!</h1>


{% endblock %}

main/templates/editreview.html
{% extends 'base.html' %}

{% block body %}


<form action="/editreview/{{review.pk}}//" method="POST">


{% csrf_token %}
{{form.as_p}}

<input type="submit" value="Edit">
</form>


{% endblock %}

main/templates/sign_up.html
{% extends 'base.html' %}

{% block body %}

<form action="/sign_up/" method="POST">

{% csrf_token %}

{{form.as_p}}

<input type="submit" value="Create User">

</form>


{% endblock %}

main/templates/signin.html
{% extends 'base.html' %}

{% block body %}

<form action="/signin/" method="POST">

{% csrf_token %}

{{form.as_p}}

<input type="submit" value="Sign In">

</form>


{% endblock %}